import os
import json
import argparse
from tqdm import tqdm

import re

import torch

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig


class TextCollator:
    
    def __init__(self, tokenizer):
        self.tokenizer = tokenizer

    def __call__(self, batch):
        sample_ids, input_ids, attention_masks = zip(*batch)

        max_length = max([ids.shape[1] for ids in input_ids])

        padded_input_ids = []
        padded_attention_masks = []

        for ids, mask in zip(input_ids, attention_masks):
            if ids.shape[1] < max_length:
                padded_input_ids.append(
                    torch.cat([ids, torch.LongTensor([self.tokenizer.pad_token_id] * (max_length - ids.shape[1])).unsqueeze(0)], dim=1)
                )
                padded_attention_masks.append(
                    torch.cat([mask, torch.LongTensor([0] * (max_length - mask.shape[1])).unsqueeze(0)], dim=1)
                )
            else:
                padded_input_ids.append(ids)
                padded_attention_masks.append(mask)
        
        padded_input_ids = torch.cat(padded_input_ids, dim=0)
        padded_attention_masks = torch.cat(padded_attention_masks, dim=0).bool()
        
        out_dict = dict(
            sample_ids=sample_ids,
            input_ids=padded_input_ids,
            attention_mask=padded_attention_masks
        )
        return out_dict


class TextLoader(torch.utils.data.Dataset):
    def __init__(
        self,
        tokenizer,
        dataset_file_root: str,
        max_tokens: int,
        dataset_name: str,
        seed: int,
        base_instruction: str,
        include_distractors: bool = True,
        include_questions: bool = True
    ):
        dataset_file = os.path.join(dataset_file_root, dataset_name)
        contents = self._read_dataset_file(dataset_file)

        self.data = contents
        self.base_instruction = base_instruction
        self.include_distractors = include_distractors
        self.include_questions = include_questions

        #if self.include_distractors:
        #    self.base_instruction += "\n.Consider that the new answer has to be differentiated from the other options. Also consider that the other options need to be plausible answers to the question."

        # Tokenizer
        self.tokenizer = tokenizer
        self.tokenizer.padding_side = "left"
        self.max_tokens = max_tokens

    def _read_dataset_file(self, dataset_file):
        with open(dataset_file) as f:
            contents = f.read()
        contents = json.loads(contents)
        return contents        

    def preprocess_string_for_eval(self, x):
        x = x.rstrip().lstrip()
        x = x.lower()
        return x

    def __getitem__(self, i):

        item = self.data[i]
        sample_id = item['id']
        question = item['question']
        answer = item['answer']
        choices = item.get('choices', [])
        choices = [str(item) for item in choices if item is not None] # Remove none types and cast to string

        sample = f"{self.base_instruction.lower().strip()}"

        if self.include_questions:
            sample += f"\nQuestion: {question}"
        if self.include_distractors:
            sample += f"\nChoices: {', '.join(choices)}"

        sample += f"\nOriginal Answer: {answer}\nRephrased Answer:"

        text = self.tokenizer(
                sample,
                max_length=self.max_tokens,
                padding="longest",
                truncation="only_first",
                return_tensors="pt"
        )
  
        return (sample_id, text["input_ids"], text["attention_mask"])

    def __len__(self):
        return len(self.data)



def process_rephrased_text(rephrased_text: str) -> str:
    """
    Extract a clean rephrased sentence from model output.
    
    Strategies (in order):
    1. Extract text between <rewrite>...</rewrite> tags
    2. Remove common prefixes and clean up
    3. Use the last non-empty line
    4. Truncate to the first sentence if necessary
    
    Args:
        rephrased_text (str): Raw text generated by the model.
        
    Returns:
        str: Clean rephrased sentence.
    """
    output_text = rephrased_text.strip()
    
    # 1. Try regex for <rewrite> tags first
    match = re.search(r"<rewrite>(.*?)</rewrite>", output_text, re.DOTALL)
    if match:
        candidate = match.group(1).strip()
    else:
        # 2. Fallback: get all non-empty lines and use the last one
        lines = [line.strip() for line in output_text.splitlines() if line.strip()]
        if lines:
            candidate = lines[-1]
        else:
            candidate = output_text

    # 3. Remove common prefixes and patterns
    # Remove prefixes like "Answer:", "The rephrased answer is:", etc.
    candidate = re.sub(r'^(Answer|The rephrased answer is?|Rephrased Answer|Response):\s*', '', candidate, flags=re.IGNORECASE).strip()
    
    # Remove "of the original answer:" patterns
    candidate = re.sub(r'^of the original answer:\s*', '', candidate, flags=re.IGNORECASE).strip()
    
    # Remove markdown headers and incomplete responses
    candidate = re.sub(r'^#+\s*(Rephrased Answer|Answer).*?$', '', candidate, flags=re.MULTILINE | re.IGNORECASE).strip()
    
    # Remove "answer:" at the beginning (lowercase)
    candidate = re.sub(r'^answer:\s*', '', candidate, flags=re.IGNORECASE).strip()

    # 4. Final processing: truncate to first sentence if needed
    if candidate:
        sentences = re.split(r'(?<=[.!?])\s+', candidate.strip())
        result = sentences[0].strip() if sentences and sentences[0].strip() else candidate
    else:
        result = rephrased_text.strip()  # Fallback to original if everything else fails
    
    return result


def rephrase_questions(args):
    """
    Reads questions from an input file, rephrases them using a prompt, and writes the rephrased questions to an output file.
    """

    #base_prompt = """
    #You are helping to rephrase the ground truth answer for a question-answering system.
    #For each answer, provide a rephrased version that maintains the original meaning but uses different wording.
    #The rephrased answer should be clear and concise, suitable to answer the question without losing meaning of the original answer.
    #Avoid including any additional information or context that is not present in the original answer.
    #"""

    base_prompt = """
    You are helping to rephrase the ground truth answer for a question-answering system.

    Instruction:
    - Rewrite the answer into exactly one alternative phrasing.
    - The rephrased answer must be clear and concise.
    - Use only the information from the original answer, without removing or adding new details or context.
    - Return the rephrased answer inside <rewrite>...</rewrite> tags.
    """

    model_name = args.model_name
    model_short_name = model_name.split("/")[-1]
    input_file = os.path.join(args.dataset_folder, args.dataset_filename)
    cache_dir = args.cache_dir

    # FIXME: I added the a2 name, to preserve previous rephrasing
    if args.include_distractors and args.include_questions:
        output_file = os.path.join(args.dataset_folder, f"rephrased-a-with-qd_{model_short_name}_{args.dataset_filename}")
    elif args.include_distractors and not args.include_questions:
        output_file = os.path.join(args.dataset_folder, f"rephrased-a-with-d_{model_short_name}_{args.dataset_filename}")
    elif not args.include_distractors and args.include_questions:
        output_file = os.path.join(args.dataset_folder, f"rephrased-a-with-q_{model_short_name}_{args.dataset_filename}")
    else:
        # NOTE: This is not a recommended setting as the model won't have enough context to rephrase properly
        output_file = os.path.join(args.dataset_folder, f"rephrased-a2_{model_short_name}_{args.dataset_filename}")
    
    if os.path.exists(output_file):
        print(f"Output file {output_file} already exists. Please remove it or choose a different model/dataset.")
        return
    
    print(f"Rephrasing answers in {input_file} using model {model_name} and saving to {output_file}")

    device = "cuda" if torch.cuda.is_available() else "cpu"

    quantization_config = BitsAndBytesConfig(
        load_in_8bit=True,
        bnb_8bit_compute_dtype=torch.bfloat16
    )

    # Download and cache the tokenizer and model locally
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        cache_dir=cache_dir,
        padding_side="left",
        )
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        cache_dir=cache_dir,
        device_map=device,
        quantization_config=quantization_config,
        torch_dtype=torch.bfloat16
        )
    model.eval()

    # Load the dataset
    dataset = TextLoader(
        tokenizer=tokenizer,
        dataset_file_root=args.dataset_folder,
        max_tokens=args.max_tokens,
        dataset_name=args.dataset_filename,
        base_instruction=base_prompt,
        seed=args.seed,
        include_distractors=args.include_distractors,
        include_questions=args.include_questions
    )

    # Prepare the DataLoader
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        collate_fn=TextCollator(tokenizer),
        num_workers=args.num_workers,
    )

    rephrased_answers = []

    # Iterate through the DataLoader and rephrase questions with tqdm
    for batch in tqdm(dataloader, desc="Rephrasing questions"):
        sample_ids = batch['sample_ids']
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)

        # get input len
        max_length_tokens = len(input_ids[0]) + 30

        # Generate rephrased questions
        with torch.no_grad():
            outputs = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_length=max_length_tokens,  # Allow some extra tokens for the output
                max_new_tokens=30,
                early_stopping=True,
                do_sample=False,
                num_beams=3,
                num_return_sequences=1,
            )

        # Remove input prompts from the rephrased texts
        outputs = outputs[:, input_ids.shape[1]:]

        # Decode the generated outputs
        rephrased_texts = tokenizer.batch_decode(outputs, skip_special_tokens=True)

        # Process the rephrased texts and store them
        for rephrased_text, sample_id in zip(rephrased_texts, sample_ids):
            # rephrased text post-process:
            rephrased_answer = process_rephrased_text(rephrased_text)

            rephrased_answers.append({
                "id": sample_id,
                "rephrased": rephrased_answer  # Take the first line as the rephrased question
            })

    # Generate a new JSON version replacing original questions with rephrased ones
    # Read original dataset file
    with open(input_file, 'r') as f:
        original_questions = json.load(f)

    new_dataset = []
    
    for sample in original_questions:
        sample_id = sample['id']
        # Find the rephrased answer for this sample_id
        rephrased_sample = next((q for q in rephrased_answers if q['id'] == sample_id), None)
        if rephrased_sample:
            original_answer = sample['answer']
            sample['answer'] = rephrased_sample['rephrased']
            # Remove the original answer from the choices and add the rephrased answer
            # Ensure original position is kept by removing and appending
            if original_answer in sample['choices']:
                original_index = sample['choices'].index(original_answer)
                sample['choices'].remove(original_answer)
                sample['choices'].insert(original_index, rephrased_sample['rephrased'])
            elif "mmsu" in args.dataset_filename.lower():
                # Try to find the closest match using difflib
                if "middle aged adult" == original_answer:
                    original_index = sample['choices'].index("Middle-aged adult")
                    sample['choices'].remove("Middle-aged adult")
                    sample['choices'].insert(original_index, rephrased_sample['rephrased'])
                elif "elderly adult" == original_answer:
                    original_index = sample['choices'].index("Elderly adult")
                    sample['choices'].remove("Elderly adult")
                    sample['choices'].insert(original_index, rephrased_sample['rephrased'])
                else:
                    print(f"Warning: answer '{original_answer}' not found in choices for id '{sample_id}' and no close match found")
                    # Put rephrased answer in the first position if not found
                    sample['choices'].insert(0, rephrased_sample['rephrased'])
            else:
                sample['choices'].insert(0, rephrased_sample['rephrased'])
        new_dataset.append(sample)
    
    # Write the rephrased questions to the output file
    with open(output_file, 'w') as f:
        json.dump(new_dataset, f, indent=4)


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Rephrase questions in a file.")
    parser.add_argument(
        '--dataset_folder',
        type=str,
        required=True,
        help='Path to the dataset file root'
        )
    parser.add_argument(
        '--dataset_filename',
        type=str,
        required=True,
        help='Name of the dataset'
        )
    parser.add_argument(
        "--model_name",
        type=str,
        required=True,
        help="Name of the pre-trained model to use for rephrasing.",
    )
    parser.add_argument(
        "--cache_dir",
        type=str,
        default='models/',
        help="Directory to cache the model",
    )
    parser.add_argument(
        '--batch_size',
        type=int,
        default=4,
        help='Batch size for dataloader'
        )
    parser.add_argument(
        '--num_workers',
        type=int,
        default=2,
        help='Number of workers for dataloader'
        )
    parser.add_argument(
        '--max_tokens',
        type=int,
        default=512,
        help='Max tokens for dataloader'
        )
    parser.add_argument(
        '--seed',
        type=int,
        default=0,
        help='Random seed for reproducibility'
        )

    # Add distractors within the prompt
    parser.add_argument(
        '--not_include_distractors',
        dest='include_distractors',
        action='store_false',
        default=True,
        help='Whether to include ground truth in the prompt'
        )

    # Add questions within the prompt
    parser.add_argument(
        '--not_include_questions',
        dest='include_questions',
        action='store_false',
        default=True,
        help='Whether to include questions in the prompt'
    )

    args = parser.parse_args()

    rephrase_questions(args)
